### PR TITLE
Correct spelling ("kinf" -> "kind")

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by ccharly** [comment]
Hi, I'm not sure about the `BUILD.TXT` file in that PR? Could you remove it? Thanks. :)

**Comment by eschnett** [comment]
D'oh.

**Comment by ccharly** [comment]
I might wait a bit more for this one, as you might find some other typos in the doc! ;)

**Comment by eschnett** [comment]
Maybe... I'm now done evaluating nsimd, and a crucial missing feature are masked store operations (#23). I'd be happy to contribute if you briefly outline the design. (By default, I'd add a new file `storeu_masked` and mostly follow OpenCL conventions.)

**Comment by eschnett** [comment]
I'm closing this in favour of #30.

**Pull request closed without merging**
